const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE'
const CLEAR_USER_ROOM = 'CLEAR_USER_ROOM';

export {
    AUTHENTICATE_USER,
    LOGOUT_USER,
    CHECK_AUTH_STATE,
    CLEAR_USER_ROOM

}