const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE'

export {
    AUTHENTICATE_USER,
    LOGOUT_USER,
    CHECK_AUTH_STATE,

}